[package]
name = "expr1-rust-ipfs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-api = "0.14.0"
ipfs-api-backend-hyper = "0.3.0"
tokio = { version="1.14.0", features = ["full"] }
